// Generated by gencpp from file beginner_tutorials/Add.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ADD_H
#define BEGINNER_TUTORIALS_MESSAGE_ADD_H

#include <ros/service_traits.h>


#include <beginner_tutorials/AddRequest.h>
#include <beginner_tutorials/AddResponse.h>


namespace beginner_tutorials
{

struct Add
{

typedef AddRequest Request;
typedef AddResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Add
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::Add > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_tutorials::Add&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::Add > {
  static const char* value()
  {
    return "beginner_tutorials/Add";
  }

  static const char* value(const ::beginner_tutorials::Add&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::AddRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Add > 
template<>
struct MD5Sum< ::beginner_tutorials::AddRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Add >::value();
  }
  static const char* value(const ::beginner_tutorials::AddRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::AddRequest> should match 
// service_traits::DataType< ::beginner_tutorials::Add > 
template<>
struct DataType< ::beginner_tutorials::AddRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Add >::value();
  }
  static const char* value(const ::beginner_tutorials::AddRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::AddResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Add > 
template<>
struct MD5Sum< ::beginner_tutorials::AddResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Add >::value();
  }
  static const char* value(const ::beginner_tutorials::AddResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::AddResponse> should match 
// service_traits::DataType< ::beginner_tutorials::Add > 
template<>
struct DataType< ::beginner_tutorials::AddResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Add >::value();
  }
  static const char* value(const ::beginner_tutorials::AddResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ADD_H
