// Generated by gencpp from file chapter4/SetSpeedRequest.msg
// DO NOT EDIT!


#ifndef CHAPTER4_MESSAGE_SETSPEEDREQUEST_H
#define CHAPTER4_MESSAGE_SETSPEEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chapter4
{
template <class ContainerAllocator>
struct SetSpeedRequest_
{
  typedef SetSpeedRequest_<ContainerAllocator> Type;

  SetSpeedRequest_()
    : desired_speed(0.0)  {
    }
  SetSpeedRequest_(const ContainerAllocator& _alloc)
    : desired_speed(0.0)  {
  (void)_alloc;
    }



   typedef float _desired_speed_type;
  _desired_speed_type desired_speed;




  typedef boost::shared_ptr< ::chapter4::SetSpeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chapter4::SetSpeedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetSpeedRequest_

typedef ::chapter4::SetSpeedRequest_<std::allocator<void> > SetSpeedRequest;

typedef boost::shared_ptr< ::chapter4::SetSpeedRequest > SetSpeedRequestPtr;
typedef boost::shared_ptr< ::chapter4::SetSpeedRequest const> SetSpeedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chapter4::SetSpeedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chapter4::SetSpeedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chapter4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chapter4::SetSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chapter4::SetSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chapter4::SetSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chapter4::SetSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chapter4::SetSpeedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chapter4::SetSpeedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chapter4::SetSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d5008c9d834e2c102355282755ead21";
  }

  static const char* value(const ::chapter4::SetSpeedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d5008c9d834e2c1ULL;
  static const uint64_t static_value2 = 0x02355282755ead21ULL;
};

template<class ContainerAllocator>
struct DataType< ::chapter4::SetSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chapter4/SetSpeedRequest";
  }

  static const char* value(const ::chapter4::SetSpeedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chapter4::SetSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 desired_speed\n\
";
  }

  static const char* value(const ::chapter4::SetSpeedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chapter4::SetSpeedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.desired_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetSpeedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chapter4::SetSpeedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chapter4::SetSpeedRequest_<ContainerAllocator>& v)
  {
    s << indent << "desired_speed: ";
    Printer<float>::stream(s, indent + "  ", v.desired_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHAPTER4_MESSAGE_SETSPEEDREQUEST_H
