// Generated by gencpp from file chapter4/SetSpeed.msg
// DO NOT EDIT!


#ifndef CHAPTER4_MESSAGE_SETSPEED_H
#define CHAPTER4_MESSAGE_SETSPEED_H

#include <ros/service_traits.h>


#include <chapter4/SetSpeedRequest.h>
#include <chapter4/SetSpeedResponse.h>


namespace chapter4
{

struct SetSpeed
{

typedef SetSpeedRequest Request;
typedef SetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeed
} // namespace chapter4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chapter4::SetSpeed > {
  static const char* value()
  {
    return "7baf09683aadda2fb755474c2726a14c";
  }

  static const char* value(const ::chapter4::SetSpeed&) { return value(); }
};

template<>
struct DataType< ::chapter4::SetSpeed > {
  static const char* value()
  {
    return "chapter4/SetSpeed";
  }

  static const char* value(const ::chapter4::SetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::chapter4::SetSpeedRequest> should match 
// service_traits::MD5Sum< ::chapter4::SetSpeed > 
template<>
struct MD5Sum< ::chapter4::SetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chapter4::SetSpeed >::value();
  }
  static const char* value(const ::chapter4::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chapter4::SetSpeedRequest> should match 
// service_traits::DataType< ::chapter4::SetSpeed > 
template<>
struct DataType< ::chapter4::SetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::chapter4::SetSpeed >::value();
  }
  static const char* value(const ::chapter4::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chapter4::SetSpeedResponse> should match 
// service_traits::MD5Sum< ::chapter4::SetSpeed > 
template<>
struct MD5Sum< ::chapter4::SetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chapter4::SetSpeed >::value();
  }
  static const char* value(const ::chapter4::SetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chapter4::SetSpeedResponse> should match 
// service_traits::DataType< ::chapter4::SetSpeed > 
template<>
struct DataType< ::chapter4::SetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::chapter4::SetSpeed >::value();
  }
  static const char* value(const ::chapter4::SetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHAPTER4_MESSAGE_SETSPEED_H
